version: "3.8"

services:
    web:
        build: .
        ports:
            - "80:3000"
        volumes:
            - ".:/app"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            - TZ=Australia/Sydney